version: '3.8'

services:
  # Apache server
  apache-server:
    container_name: php_apache
    build:
      context: ./
      dockerfile: ./zdocker/php.dockerfile
    ports:
      - "80:80"
    volumes:
      - ./Web:/var/www/html/:rw
    networks:
      - DRP
    depends_on:
      - mysql-db

  # Database using MySQL
  mysql-db:
    build:
      context: ./
      dockerfile: ./zdocker/mysql.dockerfile
    container_name: mysql_db
    ports:
      - "3306:3306"
    volumes:
      - ./Data/mysql:/var/lib/mysql
    networks:
      - DRP

  # Redis for caching and more
  redis_cache:
    image: redis:7.2.4
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - DRP

  # GUI control page
  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db-mysql
      - PMA_PORT=3306
    networks:
      - DRP

networks:
  DRP:
    driver: bridge
    ipam:
      config:
        - subnet: "172.21.0.0/16"